import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tech Terms",
  description: "Generated by Khan_Muhammad_Rifat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto text-slate-900 mt-1 sticky">
          <header className="p-6 border-b flex items-center justify-between bg-blue-500 rounded-lg rounded-br-lg">
            <div>
              <Link className="text-white text-2xl font-bold" href={"/"}>
                Tech Terms
              </Link>
              <p className="text-white text-xs px-1">Interpretation of technology related terminology</p>
              <p className="text-white text-xs px-1 py-1">Developed by <strong  className="text-black hover:text-white"><Link href={"https://www.linkedin.com/in/khan1203"}>Khan Muhammad Rifat</Link></strong></p>
            </div>
            <Link
              className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md"
              href={"/create"}
            >
              Add New
            </Link>
          </header>
          <main className="p-4 text-lg">{children}</main>
        </div>
      </body>
    </html>
  );
}
